### ISSUE TITLE
Instalation issue with python-sword

### ISSUE THREAD

**Issue by alerque** [openscriptures/Biblelator#1]
I have **python-sword-1.7.4** installed on my system (and it's obviously being found because if I uninstall it I get errors about not having it installed), but am unable to run even `./Biblelator.py --version`. I get the following message:

```
Traceback (most recent call last):
  File "./Biblelator.py", line 68, in <module>
    from BibleResourceWindows import SwordBibleResourceWindow, InternalBibleResourceWindow, DBPBibleResourceWindow
  File "/home/caleb/scratch/BiblelatorFiles/Biblelator/BibleResourceWindows.py", line 56, in <module>
    from SwordResources import SwordType
  File "../BibleOrgSys/SwordResources.py", line 59, in <module>
    Sword.FMT_TEI:'TEI', Sword.FMT_XHTML:'XHTML', Sword.FMT_LATEX:'LaTeX' }
AttributeError: module 'Sword' has no attribute 'FMT_LATEX'
```

Is there some minimum  version or compile time options that need to be met  in order for my sword/python-sword installations to be useful to Biblelator? If so are they documented somewhere?

**Comment by RobH123** [comment]
```
Hi Caleb,

    Yes, it seems that's not defined in 1.7.4. I wasn't aware of
that. Anyway, it's not very important to Biblelator, you can delete
that whole last bit "Sword.FMT_LATEX:'LaTeX'" out of
SwordResources.py in order to get to the next step.

Robert.

On 24/03/16 21:00, Caleb Maclennan
  wrote:


  I have python-sword-1.7.4 installed on my
    system (and it's obviously being found because if I uninstall it
    I get errors about not having it installed), but am unable to
    run even ./Biblelator.py --version. I get the
    following message:
  Traceback (most recent call last):
```

  File "./Biblelator.py", line 68, in <module>
    from BibleResourceWindows import SwordBibleResourceWindow, InternalBibleResourceWindow, DBPBibleResourceWindow
  File "/home/caleb/scratch/BiblelatorFiles/Biblelator/BibleResourceWindows.py", line 56, in <module>
    from SwordResources import SwordType
  File "../BibleOrgSys/SwordResources.py", line 59, in <module>
    Sword.FMT_TEI:'TEI', Sword.FMT_XHTML:'XHTML', Sword.FMT_LATEX:'LaTeX' }
AttributeError: module 'Sword' has no attribute 'FMT_LATEX'

```
  Is there some minimum version or compile time options that need
    to be met in order for my sword/python-sword installations to be
    useful to Biblelator? If so are they documented somewhere?
```

**Comment by RobH123** [comment]
I've commited a fix for this to the BibleOrgSys. Let me know if it works.

**Comment by alerque** [comment]
That commit does seem to get past at least that issue. Since 1.7.4 is the current release version (as far as I can tell) i agree it makes sense to code around it as you did at least in the master branch.
